### ISSUE TITLE
As a consumer, create appliance based on a flist

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/jumpscaleX_threebot#137]
**Assumptions**
 most of UI is ready for this

**More info**

Before implementation; please add to this issue:
- What will technically happen with this data, what is 'creating a farm'

![image](https://user-images.githubusercontent.com/7849505/67499117-d0276400-f680-11e9-9faf-df55f1f259ea.png)

![image](https://user-images.githubusercontent.com/7849505/67499159-e503f780-f680-11e9-9e40-5376bacd1599.png)

**DOD**
- Actors are working and tested
- UI is linked to actors

**TODO**

UI

- [ ]  add text/add button in appstore
- [ ]  add popover : - name application, description, flist file, info, cancel &  install
- [ ]  when removing application, show warning
