### ISSUE TITLE
Community building package

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_threebot#159]
This story card addresses the tooling needed to onboard a 3bot user to our community seamlessly.

### Description
Through a chatbot in the community package, the 3bot user will be asked about their information and interests and will be automatically subscribed to relevant spaces on our freeflowpages.

If the user has an invitation code to a space, they immediately join the space.

**Comment by BolaNasr** [comment]
**Checklist**:
In actor side:
- [ ] check invitation code is correct 
    - get what space he want to join  & the user he invited him

- [ ] join space in FFP
    - get all information from him and then join him to space he is interested  

- [ ] unsubscribe from space
    - can leave any space in FFP using FFP client

chat flow :
make chat page to interact with user :
- [ ] Question 1:
- DO you have an invitation code (Invitation code = Yes)
- ask invitation code
- invitation code allows us to track who brought who
- Invitation code = No
   - Request membership

- [ ] Question 2:
- Ask Email address
- Ask reason for interest
- Ask if you know someone in threefold or if someone referred you
- We will manually check

- [ ] Question 4:

- Which topics interest you, mention we will put them as members in the right groups on FFP and they can always unsubscribe when they want

**Comment by BolaNasr** [comment]
### Model

```
@url = community.app.1
name** = "" (S)
topic** = "" (S)
code** = (S)


@url = user.app.1
email** = (S)
interest = (S)
code** = (S)
topics = (S)
county = (S)
invited_by = (S)
community = (LS) !community.app.1


```

**Comment by BolaNasr** [comment]
@despiegk  can please review those specs 

commit : https://github.com/threefoldtech/jumpscaleX_threebot/commit/193b827b6bf30666d46fd0470037198e1dbaf7fc

**Comment by despiegk** [comment]
specs wrong, see the code.
Please link the gdoc to this ticket

**Comment by BolaNasr** [comment]
@despiegk  i added gdoc on ticket , can please push your changes in code

**Comment by BolaNasr** [comment]
**our FLow works Good :**
1- aouth get your email 
2- chatflow if you have referral code or not 
3- dynamic macros that got all spaces in FFP that's you are  member on it using your email

**TODO :** 
1 - get latest news in spaces and add it in macros
2- check if referral code validate or not

**Comment by BolaNasr** [comment]
got latest news in every spaces and add it in macros **DONE**

**development_community_app** branch
can check : https://community.app.3bot.testnet.grid.tf/chat

**Comment by BolaNasr** [comment]
Updates :
1- 3bot login and get email and username
2- Get all spaces from FFP and add it in list of interests 
3-  if  user have account in FFP will join all spaces interested in
4-  got latest news in every spaces and add it in macros

TODO : 
1- create account in FFP using email and user only ( BUG in FFP client will fix it)
2- check if referral code valid or not and get all informtaion from it

**Comment by abom** [comment]
I added support for markdown in dynamic_content macro 

https://github.com/threefoldtech/jumpscaleX_libs/pull/36
https://github.com/threefoldtech/jumpscaleX_threebot/pull/219

**Comment by BolaNasr** [comment]
First to join our FFP should invited by someone Like :
```
https://142.93.189.88/chat/session/community_join?referral=9f58d45c187d4570bf9d3d601159e22d
```
if you are admin join this to get your referral code and continue in process
```
https://142.93.189.88/chat/session/community_join_master
```
