### ISSUE TITLE
wiki improvements 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#226]
- [x]  [gpdf and googledrive macros](https://github.com/threefoldtech/jumpscaleX_threebot/issues/217)
- [x] [/docs doesn't have to be in the url if it exists in the repo root](https://github.com/threefoldtech/jumpscaleX_threebot/issues/227)
- [x] wiki load/reload shouldn't start myjobs manually (myjobs should be already started in the 3bot): FIXED [here](https://github.com/threefoldtech/jumpscaleX_core/commit/33253cf64e9a48fd24dbc7299fc1b0c5a0bf361b)
- [x] [search problems](https://github.com/threefoldtech/jumpscaleX_threebot/issues/208) 
- [x] `threebot-test -d -w -p` to be part of our test suite : [Ticket is here](https://github.com/threefoldtech/jumpscaleX_threebot/issues/235)
-  [x] [tfgrid loads without sidebar](https://github.com/threefoldtech/jumpscaleX_threebot/issues/228)

# the remaining are moved to another milestone

https://github.com/threefoldtech/jumpscaleX_threebot/issues/245

**Comment by serboctor** [comment]
@despiegk we created this issue to keep track of all the wiki changes you requested. If need more changes or have any concerns, please add them here or let us now.

**Comment by xmonader** [comment]
will continue in https://github.com/threefoldtech/jumpscaleX_threebot/issues/245

**Comment by Pishoy** [comment]
issue with step 5, https://github.com/threefoldtech/jumpscaleX_threebot/issues/235

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/issues/235 is unblocked now

**Comment by Pishoy** [comment]
verified 
 - jsx version
```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit d06d076fc80a78238ccd52b5fc0ce864ae041aa8 (HEAD -> development, origin/development, origin/HEAD)
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Nov 20 13:22:13 2019 +0200

    Change on going deployment message

```
