### ISSUE TITLE
wiki improvements 2

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#245]
- [x] [wiki loading time](https://github.com/threefoldtech/jumpscaleX_threebot/issues/209)
- [x] wiki reload (problems to reload wiki that weren't added correctly)
- [x] [wiki reload untracked changed files](#149)
(https://github.com/threefoldtech/jumpscaleX_threebot/issues/235)
- [x] [google api client to be part of core deps](https://github.com/threefoldtech/jumpscaleX_core/issues/197https://github.com/threefoldtech/jumpscaleX_core/issues/197) (will do later so we don't break the current images)
